name: anaheim_technologies_website
description: Anaheim Technologies website.
version: 1.0.0+3
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^4.6.0
  collection: ^1.17.0
  firebase_core: ^2.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: 0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  gap: 3.0.1
  go_router: ^6.5.2
  google_fonts: ^4.0.4
  intl: ^0.18.1
  logging: ^1.1.1
  url_launcher: ^6.1.10

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/
  fonts:
    - family: Plavsky
      fonts:
        - asset: fonts/Plavsky.otf
    - family: Mechsuit
      fonts:
        - asset: fonts/Mechsuit.otf

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFF"
    theme_color: "#FFF"
